Q1: Write a function to compute 5/0 and use try/except to catch the exceptions.

In [17]:
inp=5
try:
    oup = inp/0
    print(oup)
except Exception as e:
    print("Error is:", e)
    

Error is: division by zero


<img src ="1a.png">

Q2:
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [4]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            a = i+" "+j+" "+k
            print(a)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


<img src = "2a.png">

Q3: Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [10]:
import numpy as np
a = np.array([1,2,3,4,5]) 
n = 3
k = np.array([j**(n-1-i) for j in a for i in range(n)]).reshape(a.size,n)
print(k)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


<img src = "3a.png">